In [1]:
import numpy as np

 # np.array()로 ndarray() 생성

In [2]:
# 1차원 생성
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
list1 = [1, 2, 3]
print(list1, type(list1))

array1 = np.array(list1)
print(array1, type(array1))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [4]:
# 2차원 생성
array2 = np.array([[1,2,3],
                  [4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

 # shape로 nd.array() 형태 알아보기

In [5]:
array1.shape

# "1행 3열"이라는 뜻, 1차원임

(3,)

In [6]:
array2.shape

# "2행 3열"이라는 뜻, 2차원임

(2, 3)

In [7]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

# 밑에는 명백한 2차원 배열임
array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


 # dtype으로 nd.array 데이터 타입 알아보기

 - nd.array 내의 데이터 값은 숫자, 문자, 불 값이 모두 가능합니다
 - 숫자형의 경우 int, unsigned int, float, complex까지 모두 가능합니다 
 -  nd.array내의 데이터 타입은 특성상 같은 데이터 타입만 가능합니다. 즉, 한 개의 nd.array객체에 int형과 float형이 함께 있을 수 없습니다.

In [8]:
# nd.array의 데이터 타입은 dtype로 확인 가능하다.
array1.dtype

dtype('int32')

 # astype()으로 np.array의 데이터 타입 변환

In [9]:
array_int = np.array([7, 8, 9])
array_float = array_int.astype('float64')

print(array_float, array_float.dtype)
print(array_int, array_int.dtype)

[7. 8. 9.] float64
[7 8 9] int32


 # axis기반 연산함수

In [10]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.sum()) # 배열의 모든 element들을 합해줌

print(array2.sum(axis=0)) # axis=0 방향으로 더해줌

print(array2.sum(axis=1)) # axis=1 방향으로 더해줌

15
[3 5 7]
[6 9]


 # "arange", "zeros", "ones"를 이용해 nd.array 생성

 * arange

In [11]:
# "arange(10)"("r"이 하나다.)으로 0부터 9까지 들어간 1차원 배열 생성
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 * zeros로 영행렬 만들기

In [12]:
# 디폴트값이 float형이다.
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# dtype으로 int형으로 바꿀 수 있다.
np.zeros((3,2), dtype="int32")

array([[0, 0],
       [0, 0],
       [0, 0]])

 * ones로 모든 원소기 1인 행렬 만들기

In [14]:
# 디폴트값은 float형이다
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
# dtype로 int형으로 바꿀 수 있다.
np.ones((3,2), dtype="int32")

array([[1, 1],
       [1, 1],
       [1, 1]])

 # reshape로 nd.array의 차원과 크기 변경

In [16]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# reshape(2,5)로 2차원의 "2행 5열"의 array로 변환한다.

array1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**reshape(-1,5)에서 -1은 가변적이다는 뜻이다.**

In [18]:
# reshape(-1,5)에서 -1은 가변적이다는 뜻이다. 열을 5로 고정되어 있다.
# 열을 5로 고정시킨 상태에서 array를 변환시킨다는 뜻이다.

array1.reshape(-1,5)

#shape(2,5)로 바뀌었다.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
 # reshape(5,-1)은 5행으로 고정하고 열은 가변적인 상태로 바꾸어줌

array1.reshape(5,-1)

# shape(5,2)로 바뀜

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

 * reshape 응용

In [20]:
array1d = np.array([0,1,2,3,4])
array1d

array([0, 1, 2, 3, 4])

In [21]:
# reshape(-1,1)로 2차원 1열로 바꿔줌
array2d = array1d.reshape(-1,1)
array2d

# shape(5,1)로 바뀜, "5행 1열"임

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [22]:
# reshape(-1,)로 1차원으로 바꿔줌

array2d.reshape(-1,)

# shape(5,)로 바뀜, "1행 5열"임

array([0, 1, 2, 3, 4])

 # 데이터 세트 선택하기

 ## 인덱싱

In [24]:
array1 = np.arange(start=1, stop=10)
print(type(array1))
print(" ")
print(array1)

<class 'numpy.ndarray'>
 
[1 2 3 4 5 6 7 8 9]


In [28]:
print(array1[2], array1[-1], array1[-2], array1[0], array1[8])

3 9 8 1 9


In [30]:
array2 = array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array2[1,1]

5

 ## 슬라이싱

 ### 1차원 슬라이싱

In [34]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
array1[1:3]

array([2, 3])

In [38]:
array1[3:]

array([4, 5, 6, 7, 8, 9])

In [39]:
array1[:3]

array([1, 2, 3])

In [44]:
array1[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

 ### 2차원 슬라이싱

In [40]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
array2[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [46]:
array2[1:, 0:]

array([[4, 5, 6],
       [7, 8, 9]])

 ## 팬시 인덱싱

In [49]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
# 슬라이싱과 다르게 불연속적인 값도 가능
array2[[0,2],0:2]

array([[1, 2],
       [7, 8]])

 ## 불린 인덱싱

In [53]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
print(array1>5)
print("")
print(type(array1))

[False False False False False  True  True  True  True]

<class 'numpy.ndarray'>


In [58]:
array1d=array1[array1>5]
array1d

array([6, 7, 8, 9])

 # 행렬의 정렬 - sort()와 agsort()

 ## sort()

In [71]:
# np.sort()와 .sort() 모두 오름차순 정렬이다

In [70]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
print(" ")

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
print(" ")

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
 
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
 
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [73]:
# 내림차순 정렬

sort_array1_desc = np.sort(org_array)[::-1]
sort_array1_desc

array([9, 5, 3, 1])

In [74]:
# axis 기준 정렬

array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('행 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('열 방향으로 정렬:\n', sort_array2d_axis1)

행 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
열 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


 ## agsort()

In [78]:
# agsort()도 오름차순 정렬이다

org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [79]:
# 내림차순 정렬로 해줄라면 [::-1]을 붙여준다.

org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

[9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 점수를 오름차순으로 정렬하고
그에 따라서 사람이름도 오름차순 정렬된 점수에 맞게 정렬시켜주기

In [81]:
name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78, 95, 84, 98, 88])

# score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스 반환하고 이를 이용하여 name_array에서 name값 추출.  
sort_indices = np.argsort(score_array)
print("sort indices:", sort_indices)

name_array_sort = name_array[sort_indices]

score_array_sort = score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)

sort indices: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


 # 선형대수 연산, 행렬내적과 전치행렬

 ## 행렬내적

In [84]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


 ## 전치행렬

In [86]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
